### ISSUE TITLE
Change Favicon of Task Manager App  Description

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/task-manager#6]
We need to update the favicon of the Task Manager app to give it a unique and identifiable icon. The favicon appears in the browser tab and helps users quickly locate and recognize the app among multiple open tabs.

**Comment by doriroz** [comment]
i can take this issue

**Comment by SwapnaneelR** [comment]
hey @DhanushNehru can u assign me this issue?
/assign
